# Generated by Django 4.0.4 on 2022-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('valoration', models.IntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Nice'), (5, 'Verygood')])),
            ],
        ),
    ]
